# Usuário ---------------------------------------------
### Listar usuário
GET http://localhost:3000/usuario

### Exibir usuário
GET http://localhost:3000/usuario/af9c0d39-f395-46a1-95fc-589b2bd64faf

### Criar usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
  "nome": "Alan Miranda",
  "email": "freitas.miranda@gmail.com",
  "senha": "12345678"
}

### Alterar usuário
PATCH http://localhost:3000/usuario/af9c0d39-f395-46a1-95fc-589b2bd64faf
Content-Type: application/json

{
  "nome": "Alan Freitass"
}

###  Deletar usuário
DELETE http://localhost:3000/usuario/af9c0d39-f395-46a1-95fc-589b2bd64faf
