# Usuário ---------------------------------------------
### Listar usuário
GET http://localhost:3000/usuario

### Exibir usuário
GET http://localhost:3000/usuario/bcf95c52-61f4-45b4-bf04-735f28e99e2a

### Criar usuário
POST http://localhost:3000/usuario
Content-Type: application/json

{
  "nome": "Alan Miranda",
  "email": "freitas.miranda@gmail.com",
  "senha": "12345678"
}

### Alterar usuário
PATCH http://localhost:3000/usuario/bcf95c52-61f4-45b4-bf04-735f28e99e2a
Content-Type: application/json

{
  "nome": "Alan Freitass"
}

###  Deletar usuário
DELETE http://localhost:3000/usuario/bcf95c52-61f4-45b4-bf04-735f28e99e2a
