# Usuário ---------------------------------------------
### Listar
GET http://localhost:3000/usuario

### Exibir
GET http://localhost:3000/usuario/e26bc059-df12-4b39-93c2-e3cb8d6ecd14

### Criar
POST http://localhost:3000/usuario
Content-Type: application/json

{
  "nome": "Alan Miranda",
  "email": "freitas.miranda@gmail.com",
  "senha": "123456"
}

### Alterar
PATCH http://localhost:3000/usuario/e26bc059-df12-4b39-93c2-e3cb8d6ecd14
Content-Type: application/json

{
  "nome": "Alan Freitas"
}

### 
DELETE http://localhost:3000/usuario/3
